apiVersion: v1
kind: Service
metadata:
  name: llama-cpp
  namespace: llm
  labels:
    app: llama-cpp
    component: llm-server
spec:
  type: ClusterIP
  selector:
    app: llama-cpp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
