apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2025-12-27T01:32:37Z"
    generateName: log-analyzer-66c94c6bcf-
    generation: 1
    labels:
      app: log-analyzer
      pod-template-hash: 66c94c6bcf
    name: log-analyzer-66c94c6bcf-gq4cc
    namespace: log-analyzer
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: log-analyzer-66c94c6bcf
      uid: dba09de8-9473-4abb-a6ae-01628b237af1
    resourceVersion: "2216592"
    uid: b34fdbc7-82d6-4aab-bb2f-1f3dcd716dee
  spec:
    containers:
    - envFrom:
      - configMapRef:
          name: log-analyzer-config
      image: docker.io/library/log-analyzer:latest
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 8000
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      name: log-analyzer
      ports:
      - containerPort: 8000
        name: http
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 8000
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 3
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 256Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-cjwfl
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: node-1
    nodeSelector:
      hardware: light
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-cjwfl
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-12-27T01:32:39Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-12-27T01:32:37Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-12-27T01:32:45Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-12-27T01:32:45Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-12-27T01:32:37Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 200m
        memory: 256Mi
      containerID: containerd://a3e858d6734ab09aad61f1694398df47635858152adb7f08179c6798bab8e1f3
      image: docker.io/library/log-analyzer:latest
      imageID: sha256:5a90ef89d1592bd759310ef9062dd94a1d9fa4fc0d90b81b508c9ee0374f0e81
      lastState: {}
      name: log-analyzer
      ready: true
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 256Mi
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2025-12-27T01:32:38Z"
      user:
        linux:
          gid: 0
          supplementalGroups:
          - 0
          uid: 0
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-cjwfl
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 10.0.0.102
    hostIPs:
    - ip: 10.0.0.102
    - ip: 2601:483:5781:d70::c6e2
    phase: Running
    podIP: 10.42.0.90
    podIPs:
    - ip: 10.42.0.90
    qosClass: Burstable
    startTime: "2025-12-27T01:32:37Z"
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"log-analyzer"},"name":"log-analyzer","namespace":"log-analyzer"},"spec":{"ports":[{"name":"http","port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"app":"log-analyzer"},"type":"ClusterIP"}}
    creationTimestamp: "2025-12-27T01:02:48Z"
    labels:
      app: log-analyzer
    name: log-analyzer
    namespace: log-analyzer
    resourceVersion: "2213915"
    uid: 0dea1d44-bd85-4053-a987-00c9fb59fd30
  spec:
    clusterIP: 10.43.88.187
    clusterIPs:
    - 10.43.88.187
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: log-analyzer
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"log-analyzer"},"name":"log-analyzer","namespace":"log-analyzer"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"log-analyzer"}},"template":{"metadata":{"labels":{"app":"log-analyzer"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"log-analyzer-config"}}],"image":"docker.io/library/log-analyzer:latest","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":8000},"initialDelaySeconds":10,"periodSeconds":10,"timeoutSeconds":5},"name":"log-analyzer","ports":[{"containerPort":8000,"name":"http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":8000},"initialDelaySeconds":5,"periodSeconds":5,"timeoutSeconds":3},"resources":{"limits":{"cpu":"1000m","memory":"1Gi"},"requests":{"cpu":"200m","memory":"256Mi"}}}],"nodeSelector":{"hardware":"light"}}}}}
    creationTimestamp: "2025-12-27T01:03:54Z"
    generation: 1
    labels:
      app: log-analyzer
    name: log-analyzer
    namespace: log-analyzer
    resourceVersion: "2216596"
    uid: d855e6a8-12e5-4f8e-ae31-31ea88219c06
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: log-analyzer
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: log-analyzer
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: log-analyzer-config
          image: docker.io/library/log-analyzer:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: log-analyzer
          ports:
          - containerPort: 8000
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        nodeSelector:
          hardware: light
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-12-27T01:03:54Z"
      lastUpdateTime: "2025-12-27T01:12:21Z"
      message: ReplicaSet "log-analyzer-66c94c6bcf" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-12-27T01:32:45Z"
      lastUpdateTime: "2025-12-27T01:32:45Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-12-27T01:03:54Z"
    generation: 1
    labels:
      app: log-analyzer
      pod-template-hash: 66c94c6bcf
    name: log-analyzer-66c94c6bcf
    namespace: log-analyzer
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: log-analyzer
      uid: d855e6a8-12e5-4f8e-ae31-31ea88219c06
    resourceVersion: "2216595"
    uid: dba09de8-9473-4abb-a6ae-01628b237af1
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: log-analyzer
        pod-template-hash: 66c94c6bcf
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: log-analyzer
          pod-template-hash: 66c94c6bcf
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: log-analyzer-config
          image: docker.io/library/log-analyzer:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: log-analyzer
          ports:
          - containerPort: 8000
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        nodeSelector:
          hardware: light
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBdjCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy
      dmVyLWNhQDE3NjQzNDg5NzUwHhcNMjUxMTI4MTY1NjE1WhcNMzUxMTI2MTY1NjE1
      WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE3NjQzNDg5NzUwWTATBgcqhkjO
      PQIBBggqhkjOPQMBBwNCAAQ25s4put72uOZJTE+6CkVsi3PgJDgb6AJGaf7PuWrR
      8qzDoW8b5nKBUgLX3zE6y2d5761/3EV7h8o2WuN/Aqv/o0IwQDAOBgNVHQ8BAf8E
      BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUZ8gy9U93ulmOr1qFrsJa
      smmR/wowCgYIKoZIzj0EAwIDRwAwRAIgXD3uTRtnLW9Bbn1T6rzvlkPRZPPYLb0+
      wNMG7hhi86UCIFef9l2XoftW2ozQNEysH07oqFNNvXykHT0sv9g6Ajs8
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2025-12-27T01:02:48Z"
    name: kube-root-ca.crt
    namespace: log-analyzer
    resourceVersion: "2213903"
    uid: 96ae6410-9acb-4433-a0d8-faa83b29de2c
- apiVersion: v1
  data:
    DEPLOYMENT_ENVIRONMENT: kubernetes
    LLAMA_URL: http://llama-cpp.llm.svc.cluster.local:8080
    LOKI_URL: http://loki.logging.svc.cluster.local:3100
    MODEL_NAME: llama-3.2-3b-instruct
    OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.logging.svc.cluster.local:4317
    SERVICE_NAME: log-analyzer
    SERVICE_VERSION: 0.1.0
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"DEPLOYMENT_ENVIRONMENT":"kubernetes","LLAMA_URL":"http://llama-cpp.llm.svc.cluster.local:8080","LOKI_URL":"http://loki.logging.svc.cluster.local:3100","MODEL_NAME":"llama-3.2-3b-instruct","OTEL_EXPORTER_OTLP_ENDPOINT":"http://tempo.logging.svc.cluster.local:4317","SERVICE_NAME":"log-analyzer","SERVICE_VERSION":"0.1.0"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"log-analyzer-config","namespace":"log-analyzer"}}
    creationTimestamp: "2025-12-27T01:02:48Z"
    name: log-analyzer-config
    namespace: log-analyzer
    resourceVersion: "2213904"
    uid: 9481bdec-a23e-435a-8f9c-c4ce76a68dac
kind: List
metadata:
  resourceVersion: ""
