---
# HelmRelease for metrics-server
# Provides resource metrics API for kubectl top commands
# Deployed on: Node 1 (light hardware)
# CKA Exam: Enables "kubectl top nodes" and "kubectl top pods" - essential for troubleshooting
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  interval: 5m  # Check for updates every 5 minutes
  chart:
    spec:
      chart: metrics-server
      version: '3.12.2'  # Pin to current version
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  install:
    createNamespace: false  # Namespace created separately
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Resource limits (very lightweight)
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    # Node placement: Run on Node 1 (light hardware)
    nodeSelector:
      hardware: light

    # Args for metrics-server
    args:
      - --cert-dir=/tmp
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      - --kubelet-use-node-status-port
      - --metric-resolution=15s
      # Required for kubeadm clusters with self-signed kubelet certificates
      - --kubelet-insecure-tls

    # API service priority
    apiService:
      create: true
